# -*- coding: utf-8 -*-
"""Noise_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxwEI4j-82B5BnkKwfKgB4rnD6JqP8JN
"""

import pandas as pd

df = pd.read_excel("/content/dataset_clean_final.xlsx")

print("Filas:", df.shape[0])
print("Columnas:", df.columns.tolist())

# Definir la columna de texto

TEXT_COLUMN = "comment_body_clean_final"

# Crear copia de trabajo

df_ruido = df.copy()

# Paso 2 - Crear columna texto

df_ruido["texto"] = (
    df_ruido[TEXT_COLUMN]
    .fillna("")
    .astype(str)
    .str.strip()
)

# Paso 3 - Crear columna Noise_level

df_ruido["noise_level"] = "pending"

# Paso 4- Crear columna Noise_reason

df_ruido["noise_reason"] = ""

# Paso 5- Ver que todo se creo

df_ruido[[
    TEXT_COLUMN,
    "texto",
    "noise_level",
    "noise_reason"
]].head()

# paso 6 - Detectar Hard_Noise

# ============================================================
# REGLAS REFINADAS PARA HARD NOISE
# Solo hard_noise si el comentario completo es metadata/comando
# ============================================================

hard_noise_exact_patterns = [
    r"^/?html_details_block$",
    r"^/?hash_reference$",
    r"^/?benchmark_reference$",
    r"^/?ci_status_reference$",
    r"^/?workflow_ci$",
    r"^/?workflow_review$",
    r"^/?workflow_coordination$",
    r"^/?approval_notification$",
    r"^/?automated_bot_message$",
    r"^/?inline_code$",
    r"^/[a-zA-Z0-9_-]+$",
    r"^[a-f0-9]{7,40}$",
    r"^\s*$",
]

hard_noise_phrase_patterns = [
    r"^landed in\s+/?hash_reference$",
    r"^fixed in\s+/?hash_reference$",
    r"^merged in\s+/?hash_reference$",
    r"^closed by\s+/?hash_reference$",
]

def es_hard_noise(texto):
    texto = str(texto).strip().lower()

    for patron in hard_noise_exact_patterns:
        if re.search(patron, texto):
            return True

    for patron in hard_noise_phrase_patterns:
        if re.search(patron, texto):
            return True

    return False

import re
import pandas as pd

# Asegurar que la columna texto no tenga valores nulos
df_ruido["texto"] = df_ruido["texto"].fillna("").astype(str)

# Aplicar función de detección de hard noise
df_ruido["is_hard_noise"] = df_ruido["texto"].apply(es_hard_noise)

# Asignar nivel de ruido
df_ruido.loc[
    df_ruido["is_hard_noise"],
    "noise_level"
] = "hard_noise"

# Asignar razón
df_ruido.loc[
    df_ruido["is_hard_noise"],
    "noise_reason"
] = "Ruido duro: comando, metadata, referencia técnica o mensaje automático"

# Mostrar cantidad por nivel
print(df_ruido["noise_level"].value_counts())

# Mostrar ejemplos detectados como hard noise
display(
    df_ruido[df_ruido["noise_level"] == "hard_noise"][
        ["texto", "noise_level", "noise_reason"]
    ].head(30)
)

# Crear patrones de soft_noise

soft_noise_patterns = [
    r"needs rebase",
    r"please rebase",
    r"awaiting triage",
    r"pull request has been approved",
    r"approved",
    r"lgtm",
    r"label has been added",
    r"label has been removed",
    r"new changes are detected",
    r"new commits were pushed",
    r"cannot trigger testing",
    r"trusted user",
    r"merge conflict",
    r"ready for merge",
    r"retesting failed",
    r"assigned",
    r"closed successfully",
    r"reopened",
    r"milestone",
    r"review requested"
]

# Crear funcion detectora

def es_soft_noise(texto):
    texto = str(texto).strip().lower()

    for patron in soft_noise_patterns:
        if re.search(patron, texto):
            return True

    return False

# Aplicar detector

df_ruido["is_soft_noise"] = df_ruido["texto"].apply(es_soft_noise)

# Marcar solo los que siguen pendientes

soft_mask = (
    (df_ruido["is_soft_noise"] == True) &
    (df_ruido["noise_level"] == "pending")
)

df_ruido.loc[soft_mask, "noise_level"] = "soft_noise"

df_ruido.loc[soft_mask, "noise_reason"] = (
    "Ruido suave: mensaje operacional o de workflow sin valor sociotécnico directo"
)

# Ver conteo

df_ruido["noise_level"].value_counts()

# Ver ejemplos detectados

df_ruido[df_ruido["noise_level"] == "soft_noise"][
    ["texto", "noise_level", "noise_reason"]
].head(50)

df_ruido.loc[
    df_ruido["noise_level"] == "pending",
    "noise_level"
] = "useful"

df_ruido.loc[
    df_ruido["noise_level"] == "useful",
    "noise_reason"
] = (
    "Contenido potencialmente útil para análisis sociotécnico"
)

df_ruido["noise_level"].value_counts()

# ============================================================
# MUESTRA ESTRATIFICADA DE VALIDACIÓN DE RUIDO
# hard_noise / soft_noise / useful
# ============================================================

import pandas as pd
from google.colab import files

# ------------------------------------------------------------
# 1. Crear muestra de cada clase
# ------------------------------------------------------------

muestra_hard = df_ruido[
    df_ruido["noise_level"] == "hard_noise"
].sample(20, random_state=42)

muestra_soft = df_ruido[
    df_ruido["noise_level"] == "soft_noise"
].sample(20, random_state=42)

muestra_useful = df_ruido[
    df_ruido["noise_level"] == "useful"
].sample(20, random_state=42)

# ------------------------------------------------------------
# 2. Unir muestras
# ------------------------------------------------------------

muestra_validacion = pd.concat([
    muestra_hard,
    muestra_soft,
    muestra_useful
])

# ------------------------------------------------------------
# 3. Mezclar filas aleatoriamente
# ------------------------------------------------------------

muestra_validacion = muestra_validacion.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# ------------------------------------------------------------
# 4. Crear columnas para validación manual
# ------------------------------------------------------------

muestra_validacion["manual_validation"] = ""

muestra_validacion["corrected_noise_level"] = ""

muestra_validacion["validation_comment"] = ""

# ------------------------------------------------------------
# 5. Verificar distribución
# ------------------------------------------------------------

print("\nDistribución de clases:")
print(muestra_validacion["noise_level"].value_counts())

# ------------------------------------------------------------
# 6. Exportar archivo Excel
# ------------------------------------------------------------

output_file = "/content/muestra_validacion_ruido.xlsx"

muestra_validacion.to_excel(
    output_file,
    index=False
)

print(f"\nArchivo exportado correctamente: {output_file}")

# ------------------------------------------------------------
# 7. Descargar archivo automáticamente
# ------------------------------------------------------------

files.download(output_file)

df_ruido.to_excel(
    "/content/dataset_ruido_clasificado.xlsx",
    index=False
)

print("Dataset exportado correctamente")

# Crear dataset limpio

df_limpio = df_ruido[
    df_ruido["noise_level"] == "useful"
].copy()

# exportar dataset limpio

df_limpio.to_excel(
    "/content/dataset_limpio_final.xlsx",
    index=False
)

print("Dataset limpio exportado correctamente")

print(df_limpio.shape)

# Crear muestra final

df_limpio[[
    "texto",
    "final_cause_for_analysis",
    "predicted_label_llm"
]].sample(20, random_state=42)

# Crear dataset solo ruido
df_noise = df_ruido[
    df_ruido["noise_level"].isin([
        "hard_noise",
        "soft_noise",
        "useful"
    ])
].copy()

# Verificar cantidad
df_noise["noise_level"].value_counts()

# exportar dataset con ruido
df_noise.to_excel(
    "/content/dataset_noise_removed.xlsx",
    index=False
)

print("Dataset ruido exportado correctamente")