# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQ-JlgO5iRmM_MmpdS0AvYwooUXIgjgo
"""

# ============================================================
# FASE I. EXPLORACIÓN Y CARACTERIZACIÓN DEL DATASET
# ============================================================

print("====================================================")
print("FASE I. EXPLORACIÓN Y CARACTERIZACIÓN DEL DATASET")
print("====================================================")
print("Objetivo: comprender la estructura, calidad y distribución inicial del dataset enriquecido.")

# ============================================================
# PASO 1. CARGAR EL DATASET Y REVISAR SU ESTRUCTURA REAL
# Dataset TOP-K adaptativo
# ============================================================
!pip install -U kaleido
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.width", 1000)

# Nombre exacto del archivo Excel
file_path = "Dataset_integration_semantico_topk_final.xlsx"

df = pd.read_excel(file_path)

print("====================================================")
print("PASO 1. ESTRUCTURA GENERAL DEL DATASET")
print("====================================================")

print("Filas originales:", df.shape[0])
print("Columnas originales:", df.shape[1])

print("\nColumnas disponibles:")
print(df.columns.tolist())

print("\n====================================================")
print("IDENTIFICACIÓN DE ESTRUCTURA DEL DATASET")
print("====================================================")

# ------------------------------------------------------------
# 1. Detectar formato ancho clásico
# ------------------------------------------------------------

wide_microcause_columns = [
    col for col in df.columns
    if col.startswith("microcause_")
]

# ------------------------------------------------------------
# 2. Detectar formato TOP-K adaptativo
# ------------------------------------------------------------

topk_columns = [
    "top_microcause_ids",
    "top_microcause_names",
    "top_microcause_scores",
    "top_microcause_count"
]

available_topk_columns = [
    col for col in topk_columns
    if col in df.columns
]

print("Columnas formato ancho encontradas:", len(wide_microcause_columns))
print(wide_microcause_columns)

print("\nColumnas TOP-K encontradas:", len(available_topk_columns))
print(available_topk_columns)

print("\nInterpretación:")

if "microcause_1_id" in df.columns:
    print("El dataset está en formato ANCHO.")
    print("Cada fila representa un comentario.")
    print("Las microcausas están en columnas microcause_1, microcause_2 y microcause_3.")

elif set(topk_columns).issubset(set(df.columns)):
    print("El dataset está en formato TOP-K adaptativo.")
    print("Cada fila representa un comentario.")
    print("Las microcausas están almacenadas como listas en top_microcause_ids, top_microcause_names y top_microcause_scores.")
    print("La columna top_microcause_count indica cuántas microcausas fueron asignadas por comentario.")

else:
    print("El dataset no tiene una estructura de microcausas reconocida.")
    print("Debe revisarse si faltan columnas de microcausas o si tienen otro nombre.")

print("\n====================================================")
print("COLUMNAS CLAVE PARA EL EDA")
print("====================================================")

key_columns = [
    "repo",
    "issue_number",
    "comment_id",
    "comment_created_at",
    "comment_body_clean_final",
    "final_cause_for_analysis",
    "primary_microcause_id",
    "primary_microcause_name",
    "primary_similarity_score",
    "top_microcause_ids",
    "top_microcause_names",
    "top_microcause_scores",
    "top_microcause_count",
    "classification_status_topk",
    "microcause_confidence_level",
    "effects",
    "risks",
    "community_smells",
    "preventive_strategies",
    "corrective_strategies",
    "indicators",
    "metrics"
]

existing_key_columns = [
    col for col in key_columns
    if col in df.columns
]

missing_key_columns = [
    col for col in key_columns
    if col not in df.columns
]

print("Columnas clave existentes:", len(existing_key_columns))
print(existing_key_columns)

print("\nColumnas clave faltantes:", len(missing_key_columns))
print(missing_key_columns)

print("\nPrimeras filas:")
display(df.head())



# ============================================================
# PASO 2. CALIDAD DEL DATASET
# ============================================================

print("====================================================")
print("PASO 2. CALIDAD Y COMPLETITUD")
print("====================================================")

print("\nValores nulos por columna:")
nulls = df.isnull().sum()

display(
    nulls[nulls > 0]
    .sort_values(ascending=False)
)

print("\nPorcentaje de valores nulos:")

null_pct = (
    df.isnull().mean()*100
)

display(
    round(
        null_pct[null_pct > 0]
        .sort_values(ascending=False),
        2
    )
)

# ============================================================
# ELIMINAR COLUMNAS VACÍAS HEREDADAS
# ============================================================

df = df.drop(
    columns=[
        "true_code",
        "match"
    ],
    errors="ignore"
)

print("Columnas eliminadas:")
print(["true_code", "match"])

print("\nNueva dimensión del dataset:")
print(df.shape)

# ============================================================
# PASO 3. TIPOS DE DATOS Y FECHAS
# ============================================================

print("====================================================")
print("PASO 3. TIPOS DE DATOS Y FECHAS")
print("====================================================")

print("\nTipos de datos:")

display(
    df.dtypes
)

print("\nResumen de tipos:")

display(
    df.dtypes.value_counts()
)

# ------------------------------------------------------------
# Convertir fecha
# ------------------------------------------------------------

df["comment_created_at"] = pd.to_datetime(
    df["comment_created_at"],
    errors="coerce"
)

print("\nFecha mínima:")
print(df["comment_created_at"].min())

print("\nFecha máxima:")
print(df["comment_created_at"].max())

print("\nNúmero de comentarios con fecha válida:")
print(
    df["comment_created_at"]
    .notnull()
    .sum()
)

# ============================================================
# PASO 4. VALIDACIÓN DE LA UNIDAD DE ANÁLISIS
# ============================================================

print("====================================================")
print("PASO 4. VALIDACIÓN DE LA UNIDAD DE ANÁLISIS")
print("====================================================")

# ------------------------------------------------------------
# 4.1 Validar comentarios únicos
# ------------------------------------------------------------

total_rows = len(df)

unique_comments = df["comment_id"].nunique()

duplicated_comment_ids = df.duplicated(
    subset=["comment_id"]
).sum()

print("\nFilas totales del dataset:", total_rows)
print("Comentarios únicos:", unique_comments)
print("Comment_id duplicados:", duplicated_comment_ids)

# ------------------------------------------------------------
# 4.2 Interpretación automática
# ------------------------------------------------------------

if total_rows == unique_comments:
    print("\nInterpretación:")
    print("Cada fila representa un comentario único.")
    print("El dataset puede utilizarse directamente como dataset principal a nivel comentario.")
else:
    print("\nInterpretación:")
    print("Existen comentarios duplicados.")
    print("Será necesario revisar y depurar duplicados antes del análisis.")

# ------------------------------------------------------------
# 4.3 Revisar duplicados si existen
# ------------------------------------------------------------

if duplicated_comment_ids > 0:

    duplicated_rows = df[
        df.duplicated(
            subset=["comment_id"],
            keep=False
        )
    ].sort_values("comment_id")

    print("\nComentarios duplicados encontrados:")

    display(
        duplicated_rows[
            [
                "repo",
                "issue_number",
                "comment_id",
                "comment_body_clean_final",
                "final_cause_for_analysis",
                "primary_microcause_name"
            ]
        ]
    )
else:
    print("\nNo se encontraron comentarios duplicados.")

# ============================================================
# PASO 5. ESTRUCTURA MULTIFACTORIAL TOP-K
# ============================================================

print("====================================================")
print("PASO 5. ESTRUCTURA MULTIFACTORIAL TOP-K")
print("====================================================")

# ------------------------------------------------------------
# Distribución de microcausas por comentario
# ------------------------------------------------------------

distribution = (
    df["top_microcause_count"]
    .value_counts()
    .sort_index()
)

print("\nDistribución de microcausas por comentario:")
display(distribution)

# ------------------------------------------------------------
# Porcentajes
# ------------------------------------------------------------

distribution_pct = (
    distribution
    / len(df)
    * 100
).round(2)

print("\nPorcentaje:")
display(distribution_pct)

# ------------------------------------------------------------
# Total relaciones comentario ↔ microcausa
# ------------------------------------------------------------

total_relations = (
    df["top_microcause_count"]
    .sum()
)

print("\nNúmero total de relaciones comentario-microcausa:")
print(total_relations)

# ------------------------------------------------------------
# Promedio de microcausas por comentario
# ------------------------------------------------------------

avg_microcauses = (
    total_relations
    / len(df)
)

print("\nPromedio de microcausas por comentario:")
print(round(avg_microcauses, 2))

# ------------------------------------------------------------
# Comentarios multifactoriales
# ------------------------------------------------------------

multifactorial = (
    df["top_microcause_count"] > 1
).sum()

print("\nComentarios con múltiples microcausas:")
print(multifactorial)

print(
    "\nPorcentaje de comentarios multifactoriales:"
)

print(
    round(
        multifactorial / len(df) * 100,
        2
    ),
    "%"
)

# ============================================================
# PASO 6. DISTRIBUCIÓN DE MACROCAUSAS
# ============================================================

print("====================================================")
print("PASO 6. DISTRIBUCIÓN DE MACROCAUSAS")
print("====================================================")

macro_dist = (
    df["final_cause_for_analysis"]
    .value_counts()
)

display(macro_dist)

print("\nPorcentaje:")

macro_pct = (
    macro_dist
    / len(df)
    * 100
).round(2)

display(macro_pct)

# ============================================================
# PASO 7. DISTRIBUCIÓN DE MICROCAUSAS PRINCIPALES
# ============================================================

print("====================================================")
print("PASO 7. DISTRIBUCIÓN DE MICROCAUSAS PRINCIPALES")
print("====================================================")

micro_dist = (
    df["primary_microcause_name"]
    .value_counts()
)

display(micro_dist)

print("\nPorcentaje:")

micro_pct = (
    micro_dist
    / len(df)
    * 100
).round(2)

display(micro_pct)

# ============================================================
# FASE II. ANÁLISIS ONTOLÓGICO DE RELACIONES SOCIOTÉCNICAS
# ============================================================

print("====================================================")
print("FASE II. ANÁLISIS ONTOLÓGICO DE RELACIONES SOCIOTÉCNICAS")
print("====================================================")
print("Objetivo: analizar relaciones entre macrocausas, microcausas, community smells, efectos, riesgos y estrategias.")


# ============================================================
# PASO 8. MATRIZ MACROCAUSA ↔ MICROCAUSA PRINCIPAL
# ============================================================

print("====================================================")
print("PASO 8. MATRIZ MACROCAUSA ↔ MICROCAUSA")
print("====================================================")

matrix_macro_micro = pd.crosstab(
    df["final_cause_for_analysis"],
    df["primary_microcause_name"]
)

print("Dimensiones:")
print(matrix_macro_micro.shape)

display(matrix_macro_micro)

# Exportar
matrix_macro_micro.to_excel(
    "matrix_macro_micro.xlsx"
)

print("\nMatriz exportada:")
print("matrix_macro_micro.xlsx")

# ============================================================
# PASO 9. COOCURRENCIA MICROCAUSA ↔ MICROCAUSA
# ============================================================

import ast
import pandas as pd
from itertools import combinations
from collections import Counter

print("====================================================")
print("PASO 9. COOCURRENCIA MICROCAUSA ↔ MICROCAUSA")
print("====================================================")

pair_counter = Counter()

for micro_list in df["top_microcause_names"]:

    try:

        if isinstance(micro_list, str):
            micro_list = ast.literal_eval(micro_list)

        if not isinstance(micro_list, list):
            continue

        if len(micro_list) < 2:
            continue

        unique_microcauses = sorted(set(micro_list))

        for pair in combinations(unique_microcauses, 2):
            pair_counter[pair] += 1

    except:
        continue

pairs_df = pd.DataFrame(
    [
        {
            "microcause_1": p[0],
            "microcause_2": p[1],
            "frequency": f
        }
        for p, f in pair_counter.items()
    ]
)

pairs_df = pairs_df.sort_values(
    "frequency",
    ascending=False
)

print("\nNúmero total de pares encontrados:")
print(len(pairs_df))

print("\nTop 30 pares más frecuentes:")

display(
    pairs_df.head(30)
)

pairs_df.to_excel(
    "microcause_cooccurrence.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("microcause_cooccurrence.xlsx")

# ============================================================
# PASO 10. MATRIZ MICROCAUSA ↔ COMMUNITY SMELL
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 10. MATRIZ MICROCAUSA ↔ COMMUNITY SMELL")
print("====================================================")

# ------------------------------------------------------------
# Construir relaciones
# ------------------------------------------------------------

rows = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    smells = str(row["community_smells"])

    for smell in smells.split("•"):

        smell = smell.strip()

        if smell == "":
            continue

        rows.append({
            "microcause": microcause,
            "community_smell": smell
        })

micro_smell_df = pd.DataFrame(rows)

print("\nRelaciones encontradas:")
print(len(micro_smell_df))

# ------------------------------------------------------------
# Matriz
# ------------------------------------------------------------

matrix_micro_smell = pd.crosstab(
    micro_smell_df["microcause"],
    micro_smell_df["community_smell"]
)

print("\nDimensiones:")
print(matrix_micro_smell.shape)

display(matrix_micro_smell)

# ------------------------------------------------------------
# Exportar
# ------------------------------------------------------------

matrix_micro_smell.to_excel(
    "matrix_microcause_community_smell.xlsx"
)

print("\nArchivo exportado:")
print("matrix_microcause_community_smell.xlsx")

# ============================================================
# PASO 11. MATRIZ MICROCAUSA ↔ EFECTOS
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 11. MATRIZ MICROCAUSA ↔ EFECTOS")
print("====================================================")

rows = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    effects = str(row["effects"])

    for effect in effects.split("•"):

        effect = effect.strip()

        if effect == "":
            continue

        rows.append({
            "microcause": microcause,
            "effect": effect
        })

micro_effect_df = pd.DataFrame(rows)

print("\nRelaciones encontradas:")
print(len(micro_effect_df))

matrix_micro_effect = pd.crosstab(
    micro_effect_df["microcause"],
    micro_effect_df["effect"]
)

print("\nDimensiones:")
print(matrix_micro_effect.shape)

display(matrix_micro_effect)

# ------------------------------------------------------------
# TOP EFECTOS
# ------------------------------------------------------------

effect_freq = (
    micro_effect_df["effect"]
    .value_counts()
)

print("\nTop efectos más frecuentes:")

display(effect_freq.head(20))

matrix_micro_effect.to_excel(
    "matrix_microcause_effects.xlsx"
)

print("\nArchivo exportado:")
print("matrix_microcause_effects.xlsx")

# ============================================================
# PASO 12. MATRIZ MICROCAUSA ↔ RIESGOS
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 12. MATRIZ MICROCAUSA ↔ RIESGOS")
print("====================================================")

rows = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    risks = str(row["risks"])

    for risk in risks.split("•"):

        risk = risk.strip()

        if risk == "":
            continue

        rows.append({
            "microcause": microcause,
            "risk": risk
        })

micro_risk_df = pd.DataFrame(rows)

print("\nRelaciones encontradas:")
print(len(micro_risk_df))

matrix_micro_risk = pd.crosstab(
    micro_risk_df["microcause"],
    micro_risk_df["risk"]
)

print("\nDimensiones:")
print(matrix_micro_risk.shape)

display(matrix_micro_risk)

# ------------------------------------------------------------
# TOP RIESGOS
# ------------------------------------------------------------

risk_freq = (
    micro_risk_df["risk"]
    .value_counts()
)

print("\nTop riesgos más frecuentes:")

display(risk_freq.head(20))

matrix_micro_risk.to_excel(
    "matrix_microcause_risks.xlsx"
)

print("\nArchivo exportado:")
print("matrix_microcause_risks.xlsx")

# ============================================================
# PASO 13. MATRIZ MICROCAUSA ↔ ESTRATEGIAS PREVENTIVAS
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 13. MATRIZ MICROCAUSA ↔ ESTRATEGIAS PREVENTIVAS")
print("====================================================")

rows = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    strategies = str(row["preventive_strategies"])

    for strategy in strategies.split("•"):

        strategy = strategy.strip()

        if strategy == "":
            continue

        rows.append({
            "microcause": microcause,
            "preventive_strategy": strategy
        })

micro_strategy_df = pd.DataFrame(rows)

print("\nRelaciones encontradas:")
print(len(micro_strategy_df))

# ------------------------------------------------------------
# MATRIZ
# ------------------------------------------------------------

matrix_micro_strategy = pd.crosstab(
    micro_strategy_df["microcause"],
    micro_strategy_df["preventive_strategy"]
)

print("\nDimensiones:")
print(matrix_micro_strategy.shape)

display(matrix_micro_strategy)

# ------------------------------------------------------------
# TOP ESTRATEGIAS
# ------------------------------------------------------------

strategy_freq = (
    micro_strategy_df["preventive_strategy"]
    .value_counts()
)

print("\nTop estrategias preventivas:")

display(strategy_freq.head(30))

# ------------------------------------------------------------
# EXPORTAR
# ------------------------------------------------------------

matrix_micro_strategy.to_excel(
    "matrix_microcause_preventive_strategies.xlsx"
)

print("\nArchivo exportado:")
print("matrix_microcause_preventive_strategies.xlsx")

# ============================================================
# PASO 14. MATRIZ MICROCAUSA ↔ ESTRATEGIAS CORRECTIVAS
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 14. MATRIZ MICROCAUSA ↔ ESTRATEGIAS CORRECTIVAS")
print("====================================================")

rows = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    strategies = str(row["corrective_strategies"])

    for strategy in strategies.split("•"):

        strategy = strategy.strip()

        if strategy == "":
            continue

        rows.append({
            "microcause": microcause,
            "corrective_strategy": strategy
        })

micro_corrective_df = pd.DataFrame(rows)

print("\nRelaciones encontradas:")
print(len(micro_corrective_df))

# ------------------------------------------------------------
# MATRIZ
# ------------------------------------------------------------

matrix_micro_corrective = pd.crosstab(
    micro_corrective_df["microcause"],
    micro_corrective_df["corrective_strategy"]
)

print("\nDimensiones:")
print(matrix_micro_corrective.shape)

display(matrix_micro_corrective)

# ------------------------------------------------------------
# TOP ESTRATEGIAS CORRECTIVAS
# ------------------------------------------------------------

corrective_freq = (
    micro_corrective_df["corrective_strategy"]
    .value_counts()
)

print("\nTop estrategias correctivas:")

display(corrective_freq.head(30))

# ------------------------------------------------------------
# EXPORTAR
# ------------------------------------------------------------

matrix_micro_corrective.to_excel(
    "matrix_microcause_corrective_strategies.xlsx"
)

print("\nArchivo exportado:")
print("matrix_microcause_corrective_strategies.xlsx")

# ============================================================
# PASO 15. MATRIZ COMMUNITY SMELL ↔ EFECTOS
# ============================================================

import pandas as pd
from collections import Counter

print("====================================================")
print("PASO 15. MATRIZ COMMUNITY SMELL ↔ EFECTOS")
print("====================================================")

relations = []

for _, row in df.iterrows():

    smells = str(row["community_smells"]).split("•")
    effects = str(row["effects"]).split("•")

    smells = [
        s.strip()
        for s in smells
        if s.strip() != ""
    ]

    effects = [
        e.strip()
        for e in effects
        if e.strip() != ""
    ]

    for smell in smells:
        for effect in effects:

            relations.append({
                "community_smell": smell,
                "effect": effect
            })

df_smell_effect = pd.DataFrame(relations)

print("\nRelaciones encontradas:")
print(len(df_smell_effect))

matrix_smell_effect = pd.crosstab(
    df_smell_effect["community_smell"],
    df_smell_effect["effect"]
)

print("\nDimensiones:")
print(matrix_smell_effect.shape)

display(matrix_smell_effect)

matrix_smell_effect.to_excel(
    "matrix_community_smell_effects.xlsx"
)

print("\nArchivo exportado:")
print("matrix_community_smell_effects.xlsx")

# ============================================================
# PASO 16. TOP EFECTOS POR COMMUNITY SMELL
# ============================================================

print("====================================================")
print("PASO 16. TOP EFECTOS POR COMMUNITY SMELL")
print("====================================================")

top_effects_by_smell = []

for smell in matrix_smell_effect.index:

    row = matrix_smell_effect.loc[smell]

    top_effects = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(10)
    )

    for effect, freq in top_effects.items():

        top_effects_by_smell.append({
            "community_smell": smell,
            "effect": effect,
            "frequency": freq
        })

top_effects_df = pd.DataFrame(top_effects_by_smell)

display(top_effects_df)

top_effects_df.to_excel(
    "top_effects_by_community_smell.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("top_effects_by_community_smell.xlsx")

# ============================================================
# PASO 17. MATRIZ COMMUNITY SMELL ↔ RIESGOS
# ============================================================

print("====================================================")
print("PASO 17. MATRIZ COMMUNITY SMELL ↔ RIESGOS")
print("====================================================")

relations = []

for _, row in df.iterrows():

    smells = str(row["community_smells"]).split("•")
    risks = str(row["risks"]).split("•")

    smells = [
        s.strip()
        for s in smells
        if s.strip() != ""
    ]

    risks = [
        r.strip()
        for r in risks
        if r.strip() != ""
    ]

    for smell in smells:
        for risk in risks:

            relations.append({
                "community_smell": smell,
                "risk": risk
            })

df_smell_risk = pd.DataFrame(relations)

print("\nRelaciones encontradas:")
print(len(df_smell_risk))

matrix_smell_risk = pd.crosstab(
    df_smell_risk["community_smell"],
    df_smell_risk["risk"]
)

print("\nDimensiones:")
print(matrix_smell_risk.shape)

display(matrix_smell_risk)

matrix_smell_risk.to_excel(
    "matrix_community_smell_risks.xlsx"
)

print("\nArchivo exportado:")
print("matrix_community_smell_risks.xlsx")

# ============================================================
# PASO 18. TOP RIESGOS POR COMMUNITY SMELL
# ============================================================

print("====================================================")
print("PASO 18. TOP RIESGOS POR COMMUNITY SMELL")
print("====================================================")

top_risks = []

for smell in matrix_smell_risk.index:

    row = matrix_smell_risk.loc[smell]

    top_items = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(10)
    )

    for risk, freq in top_items.items():

        top_risks.append({
            "community_smell": smell,
            "risk": risk,
            "frequency": freq
        })

top_risks_df = pd.DataFrame(top_risks)

display(top_risks_df)

top_risks_df.to_excel(
    "top_risks_by_community_smell.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("top_risks_by_community_smell.xlsx")

# ============================================================
# PASO 19. MATRIZ COMMUNITY SMELL ↔ ESTRATEGIAS PREVENTIVAS
# ============================================================

print("====================================================")
print("PASO 19. MATRIZ COMMUNITY SMELL ↔ ESTRATEGIAS PREVENTIVAS")
print("====================================================")

relations = []

for _, row in df.iterrows():

    smells = str(row["community_smells"]).split("•")
    strategies = str(row["preventive_strategies"]).split("•")

    smells = [
        s.strip()
        for s in smells
        if s.strip() != ""
    ]

    strategies = [
        st.strip()
        for st in strategies
        if st.strip() != ""
    ]

    for smell in smells:
        for strategy in strategies:

            relations.append({
                "community_smell": smell,
                "preventive_strategy": strategy
            })

df_smell_preventive = pd.DataFrame(relations)

print("\nRelaciones encontradas:")
print(len(df_smell_preventive))

matrix_smell_preventive = pd.crosstab(
    df_smell_preventive["community_smell"],
    df_smell_preventive["preventive_strategy"]
)

print("\nDimensiones:")
print(matrix_smell_preventive.shape)

display(matrix_smell_preventive)

matrix_smell_preventive.to_excel(
    "matrix_community_smell_preventive.xlsx"
)

print("\nArchivo exportado:")
print("matrix_community_smell_preventive.xlsx")

# ============================================================
# PASO 20. TOP ESTRATEGIAS PREVENTIVAS POR COMMUNITY SMELL
# ============================================================

print("====================================================")
print("PASO 20. TOP ESTRATEGIAS PREVENTIVAS POR COMMUNITY SMELL")
print("====================================================")

top_preventive = []

for smell in matrix_smell_preventive.index:

    row = matrix_smell_preventive.loc[smell]

    top_items = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(10)
    )

    for strategy, freq in top_items.items():

        top_preventive.append({
            "community_smell": smell,
            "preventive_strategy": strategy,
            "frequency": freq
        })

top_preventive_df = pd.DataFrame(top_preventive)

display(top_preventive_df)

top_preventive_df.to_excel(
    "top_preventive_by_community_smell.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("top_preventive_by_community_smell.xlsx")

# ============================================================
# PASO 21. MATRIZ COMMUNITY SMELL ↔ ESTRATEGIAS CORRECTIVAS
# ============================================================

print("====================================================")
print("PASO 21. MATRIZ COMMUNITY SMELL ↔ ESTRATEGIAS CORRECTIVAS")
print("====================================================")

relations = []

for _, row in df.iterrows():

    smells = str(row["community_smells"]).split("•")
    strategies = str(row["corrective_strategies"]).split("•")

    smells = [
        s.strip()
        for s in smells
        if s.strip() != ""
    ]

    strategies = [
        st.strip()
        for st in strategies
        if st.strip() != ""
    ]

    for smell in smells:
        for strategy in strategies:

            relations.append({
                "community_smell": smell,
                "corrective_strategy": strategy
            })

df_smell_corrective = pd.DataFrame(relations)

print("\nRelaciones encontradas:")
print(len(df_smell_corrective))

matrix_smell_corrective = pd.crosstab(
    df_smell_corrective["community_smell"],
    df_smell_corrective["corrective_strategy"]
)

print("\nDimensiones:")
print(matrix_smell_corrective.shape)

display(matrix_smell_corrective)

matrix_smell_corrective.to_excel(
    "matrix_community_smell_corrective.xlsx"
)

print("\nArchivo exportado:")
print("matrix_community_smell_corrective.xlsx")

# ============================================================
# PASO 22. TOP ESTRATEGIAS CORRECTIVAS POR COMMUNITY SMELL
# ============================================================

print("====================================================")
print("PASO 22. TOP ESTRATEGIAS CORRECTIVAS POR COMMUNITY SMELL")
print("====================================================")

top_corrective = []

for smell in matrix_smell_corrective.index:

    row = matrix_smell_corrective.loc[smell]

    top_items = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(10)
    )

    for strategy, freq in top_items.items():

        top_corrective.append({
            "community_smell": smell,
            "corrective_strategy": strategy,
            "frequency": freq
        })

top_corrective_df = pd.DataFrame(top_corrective)

display(top_corrective_df)

top_corrective_df.to_excel(
    "top_corrective_by_community_smell.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("top_corrective_by_community_smell.xlsx")

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

data = df["top_microcause_count"].value_counts().sort_index()

bars = plt.bar(
    data.index.astype(str),
    data.values,
    color=["#BFD7EA", "#6BAED6", "#2171B5"]
)

plt.title("Distribución de microcausas por comentario", fontsize=14, fontweight="bold")
plt.xlabel("Número de microcausas asignadas")
plt.ylabel("Cantidad de comentarios")

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{int(height)}",
        ha="center",
        va="bottom",
        fontsize=11
    )

plt.tight_layout()
plt.savefig("grafico_topk_microcausas.png", dpi=300, bbox_inches="tight")
plt.show()

top_micro = df["primary_microcause_name"].value_counts().head(10)

plt.figure(figsize=(10, 6))

bars = plt.barh(
    top_micro.index[::-1],
    top_micro.values[::-1],
    color="#2171B5"
)

plt.title("Top 10 microcausas principales", fontsize=14, fontweight="bold")
plt.xlabel("Frecuencia")
plt.ylabel("Microcausa")

for bar in bars:
    width = bar.get_width()
    plt.text(
        width + 5,
        bar.get_y() + bar.get_height()/2,
        f"{int(width)}",
        va="center",
        fontsize=10
    )

plt.tight_layout()
plt.savefig("grafico_top10_microcausas.png", dpi=300, bbox_inches="tight")
plt.show()

top_risk = risk_freq.head(10)

plt.figure(figsize=(10, 6))

bars = plt.barh(
    top_risk.index[::-1],
    top_risk.values[::-1],
    color="#08519C"
)

plt.title("Top 10 riesgos asociados a la deuda social", fontsize=14, fontweight="bold")
plt.xlabel("Frecuencia")
plt.ylabel("Riesgo")

for bar in bars:
    width = bar.get_width()
    plt.text(
        width + 10,
        bar.get_y() + bar.get_height()/2,
        f"{int(width)}",
        va="center",
        fontsize=10
    )

plt.tight_layout()
plt.savefig("grafico_top10_riesgos.png", dpi=300, bbox_inches="tight")
plt.show()

top_prev = strategy_freq.head(10)

plt.figure(figsize=(10, 6))

bars = plt.barh(
    top_prev.index[::-1],
    top_prev.values[::-1],
    color="#4292C6"
)

plt.title("Top 10 estrategias preventivas", fontsize=14, fontweight="bold")
plt.xlabel("Frecuencia")
plt.ylabel("Estrategia preventiva")

for bar in bars:
    width = bar.get_width()
    plt.text(
        width + 10,
        bar.get_y() + bar.get_height()/2,
        f"{int(width)}",
        va="center",
        fontsize=10
    )

plt.tight_layout()
plt.savefig("grafico_top10_estrategias_preventivas.png", dpi=300, bbox_inches="tight")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Usar solo las 20 microcausas con mayor suma
top_microcauses = (
    matrix_micro_smell
    .sum(axis=1)
    .sort_values(ascending=False)
    .head(20)
    .index
)

heatmap_data = matrix_micro_smell.loc[top_microcauses]

plt.figure(figsize=(14, 10))

sns.heatmap(
    heatmap_data,
    cmap="Blues",
    annot=True,
    fmt="d",
    linewidths=0.5,
    cbar_kws={"label": "Frequency"}
)

plt.title(
    "Microcauses associated with Community Smells",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Community Smell")
plt.ylabel("Microcause")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()

plt.savefig(
    "heatmap_microcause_community_smell.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# Usar matriz del PASO 17
plt.figure(figsize=(16, 7))

sns.heatmap(
    matrix_smell_risk,
    cmap="Blues",
    annot=True,
    fmt="d",
    linewidths=0.5,
    cbar_kws={"label": "Frequency"}
)

plt.title(
    "Community Smells associated with Risks",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Risk")
plt.ylabel("Community Smell")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()

plt.savefig(
    "heatmap_community_smell_risk.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

!pip install -U kaleido

import kaleido
print("Kaleido instalado correctamente")

import plotly.graph_objects as go
import pandas as pd

# ============================================================
# Preparar relaciones para Sankey
# ============================================================

relations = []

for _, row in df.iterrows():

    macro = row["final_cause_for_analysis"]
    micro = row["primary_microcause_name"]

    smells = [
        s.strip()
        for s in str(row["community_smells"]).split("•")
        if s.strip() != ""
    ]

    risks = [
        r.strip()
        for r in str(row["risks"]).split("•")
        if r.strip() != ""
    ]

    for smell in smells:
        relations.append((macro, micro))

        relations.append((micro, smell))

        for risk in risks:
            relations.append((smell, risk))

relations_df = pd.DataFrame(
    relations,
    columns=["source", "target"]
)

relations_count = (
    relations_df
    .value_counts()
    .reset_index(name="value")
)

# Filtrar relaciones pequeñas para que el gráfico no quede saturado
relations_count = relations_count[
    relations_count["value"] >= 80
]

# Crear nodos
labels = pd.unique(
    relations_count[["source", "target"]].values.ravel()
).tolist()

label_to_id = {
    label: i
    for i, label in enumerate(labels)
}

sources = relations_count["source"].map(label_to_id)
targets = relations_count["target"].map(label_to_id)
values = relations_count["value"]

# ============================================================
# Sankey
# ============================================================

fig = go.Figure(
    data=[
        go.Sankey(
            node=dict(
                pad=20,
                thickness=18,
                line=dict(color="black", width=0.3),
                label=labels,
                color="#9ECAE1"
            ),
            link=dict(
                source=sources,
                target=targets,
                value=values,
                color="rgba(33, 113, 181, 0.35)"
            )
        )
    ]
)

fig.update_layout(
    title_text="Semantic Flow of Social Debt: Macrocauses, Microcauses, Community Smells and Risks",
    font_size=11,
    width=1300,
    height=850
)



fig.show()

import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

# Relaciones microcausa-community smell
for _, row in micro_smell_df.iterrows():
    G.add_edge(
        row["microcause"],
        row["community_smell"],
        weight=1
    )

# Relaciones community smell-risk
for _, row in df_smell_risk.iterrows():
    G.add_edge(
        row["community_smell"],
        row["risk"],
        weight=1
    )

# Filtrar nodos con grado alto para que sea legible
degree_dict = dict(G.degree())
important_nodes = [
    node for node, degree in degree_dict.items()
    if degree >= 5
]

G_sub = G.subgraph(important_nodes)

plt.figure(figsize=(16, 12))

pos = nx.spring_layout(
    G_sub,
    k=0.35,
    seed=42
)

nx.draw_networkx_nodes(
    G_sub,
    pos,
    node_size=600,
    node_color="#9ECAE1",
    edgecolors="#08519C"
)

nx.draw_networkx_edges(
    G_sub,
    pos,
    alpha=0.35,
    edge_color="#2171B5"
)

nx.draw_networkx_labels(
    G_sub,
    pos,
    font_size=8
)

plt.title(
    "Network of Microcauses, Community Smells and Risks",
    fontsize=16,
    fontweight="bold"
)

plt.axis("off")
plt.tight_layout()

plt.savefig(
    "network_microcause_smell_risk.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ============================================================
# FASE III. VISUALIZACIÓN CIENTÍFICA DEL ECOSISTEMA DE DEUDA SOCIAL
# ============================================================

print("====================================================")
print("FASE III. VISUALIZACIÓN CIENTÍFICA DEL ECOSISTEMA DE DEUDA SOCIAL")
print("====================================================")
print("Objetivo: generar gráficos publicables para representar patrones sociotécnicos.")

# ============================================================
# PASO 23. HEATMAP MICROCAUSA ↔ COMMUNITY SMELL CON FRECUENCIAS
# ============================================================

# ============================================================
# HEATMAP FILTRADO: TOP 15 MICROCAUSAS ↔ COMMUNITY SMELL
# ============================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

matrix = pd.read_excel(
    "matrix_microcause_community_smell.xlsx",
    index_col=0
)

# Seleccionar las 15 microcausas con mayor suma total
top_microcauses = (
    matrix.sum(axis=1)
    .sort_values(ascending=False)
    .head(15)
    .index
)

matrix_top = matrix.loc[top_microcauses]

plt.figure(figsize=(14, 9))

sns.heatmap(
    matrix_top,
    cmap="Blues",
    annot=True,
    fmt="d",
    linewidths=0.5,
    linecolor="white",
    cbar_kws={"label": "Frequency"},
    annot_kws={"size": 9}
)

plt.title(
    "Top Microcause ↔ Community Smell Relationships",
    fontsize=15,
    weight="bold"
)

plt.xlabel("Community Smell")
plt.ylabel("Microcause")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()

plt.savefig(
    "heatmap_top15_microcause_community_smell.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ============================================================
# PASO 24. HEATMAP COMMUNITY SMELL ↔ RISK CON FRECUENCIAS
# ============================================================

# ============================================================
# HEATMAP FILTRADO: COMMUNITY SMELL ↔ TOP 12 RIESGOS
# ============================================================

matrix = pd.read_excel(
    "matrix_community_smell_risks.xlsx",
    index_col=0
)

# Seleccionar los 12 riesgos más frecuentes
top_risks = (
    matrix.sum(axis=0)
    .sort_values(ascending=False)
    .head(12)
    .index
)

matrix_top = matrix[top_risks]

plt.figure(figsize=(14, 7))

sns.heatmap(
    matrix_top,
    cmap="Blues",
    annot=True,
    fmt="d",
    linewidths=0.5,
    linecolor="white",
    cbar_kws={"label": "Frequency"},
    annot_kws={"size": 9}
)

plt.title(
    "Community Smell ↔ Top Risk Relationships",
    fontsize=15,
    weight="bold"
)

plt.xlabel("Risk")
plt.ylabel("Community Smell")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()

plt.savefig(
    "heatmap_community_smell_top12_risks.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ============================================================
# FASE IV. DESCUBRIMIENTO DE CONOCIMIENTO
# ============================================================

print("====================================================")
print("FASE IV. DESCUBRIMIENTO DE CONOCIMIENTO")
print("====================================================")
print("Objetivo: sintetizar hallazgos relevantes derivados del modelo adaptativo.")

# ============================================================
# PASO 28. COMMUNITY SMELLS DOMINANTES
# ============================================================

import pandas as pd

matrix = pd.read_excel(
    "matrix_microcause_community_smell.xlsx",
    index_col=0
)

community_smell_totals = (
    matrix.sum(axis=0)
    .sort_values(ascending=False)
)

print("====================================================")
print("PASO 28. COMMUNITY SMELLS DOMINANTES")
print("====================================================")

display(
    community_smell_totals.to_frame("frequency")
)

community_smell_pct = (
    community_smell_totals /
    community_smell_totals.sum() * 100
).round(2)

print("\nPorcentaje:")
display(
    community_smell_pct.to_frame("percentage")
)

# ============================================================
# PASO 29. RIESGOS DOMINANTES
# ============================================================

matrix = pd.read_excel(
    "matrix_microcause_risks.xlsx",
    index_col=0
)

risk_totals = (
    matrix.sum(axis=0)
    .sort_values(ascending=False)
)

print("====================================================")
print("PASO 29. RIESGOS DOMINANTES")
print("====================================================")

display(
    risk_totals.to_frame("frequency")
)

# ============================================================
# PASO 30. ESTRATEGIAS PREVENTIVAS DOMINANTES
# ============================================================

matrix = pd.read_excel(
    "matrix_microcause_preventive_strategies.xlsx",
    index_col=0
)

strategy_totals = (
    matrix.sum(axis=0)
    .sort_values(ascending=False)
)

display(
    strategy_totals.head(20)
)

# ============================================================
# PASO 31. ESTRATEGIAS CORRECTIVAS DOMINANTES
# ============================================================

matrix = pd.read_excel(
    "matrix_microcause_corrective_strategies.xlsx",
    index_col=0
)

strategy_totals = (
    matrix.sum(axis=0)
    .sort_values(ascending=False)
)

display(
    strategy_totals.head(20)
)

# ============================================================
# PASO 32. RUTAS CRÍTICAS DEL MODELO ADAPTATIVO
# ============================================================

import pandas as pd

# --------------------------------------------------
# Community Smell dominante por microcausa
# --------------------------------------------------

smell_matrix = pd.read_excel(
    "matrix_microcause_community_smell.xlsx",
    index_col=0
)

top_smell_by_microcause = (
    smell_matrix.idxmax(axis=1)
)

# --------------------------------------------------
# Riesgo dominante por microcausa
# --------------------------------------------------

risk_matrix = pd.read_excel(
    "matrix_microcause_risks.xlsx",
    index_col=0
)

top_risk_by_microcause = (
    risk_matrix.idxmax(axis=1)
)

# --------------------------------------------------
# Estrategia preventiva dominante
# --------------------------------------------------

preventive_matrix = pd.read_excel(
    "matrix_microcause_preventive_strategies.xlsx",
    index_col=0
)

top_preventive = (
    preventive_matrix.idxmax(axis=1)
)

# --------------------------------------------------
# Construcción de rutas
# --------------------------------------------------

critical_paths = pd.DataFrame({
    "microcause": smell_matrix.index,
    "dominant_community_smell": top_smell_by_microcause.values,
    "dominant_risk": top_risk_by_microcause.values,
    "dominant_preventive_strategy": top_preventive.values
})

print("====================================================")
print("PASO 32. RUTAS CRÍTICAS")
print("====================================================")

display(
    critical_paths.head(20)
)

critical_paths.to_excel(
    "critical_paths_social_debt.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("critical_paths_social_debt.xlsx")

# ============================================================
# PASO 33. MICROCAUSAS ESTRUCTURALES
# ============================================================

import pandas as pd

smells = pd.read_excel(
    "matrix_microcause_community_smell.xlsx",
    index_col=0
)

risks = pd.read_excel(
    "matrix_microcause_risks.xlsx",
    index_col=0
)

effects = pd.read_excel(
    "matrix_microcause_effects.xlsx",
    index_col=0
)

structural_score = pd.DataFrame({
    "community_smells": (smells > 0).sum(axis=1),
    "risks": (risks > 0).sum(axis=1),
    "effects": (effects > 0).sum(axis=1)
})

structural_score["total_connections"] = (
    structural_score.sum(axis=1)
)

structural_score = (
    structural_score
    .sort_values(
        "total_connections",
        ascending=False
    )
)

print("====================================================")
print("PASO 33. MICROCAUSAS ESTRUCTURALES")
print("====================================================")

display(structural_score.head(20))

# ============================================================
# PASO 34. COMMUNITY SMELLS ESTRUCTURALES
# ============================================================

import pandas as pd

# Matrices ya exportadas
smell_risk = pd.read_excel(
    "matrix_community_smell_risks.xlsx",
    index_col=0
)

smell_preventive = pd.read_excel(
    "matrix_community_smell_preventive.xlsx",
    index_col=0
)

smell_corrective = pd.read_excel(
    "matrix_community_smell_corrective.xlsx",
    index_col=0
)

# Si ya tienes matrix_community_smell_effects.xlsx
smell_effects = pd.read_excel(
    "matrix_community_smell_effects.xlsx",
    index_col=0
)

smell_structural_score = pd.DataFrame({
    "effects": (smell_effects > 0).sum(axis=1),
    "risks": (smell_risk > 0).sum(axis=1),
    "preventive_strategies": (smell_preventive > 0).sum(axis=1),
    "corrective_strategies": (smell_corrective > 0).sum(axis=1)
})

smell_structural_score["total_connections"] = (
    smell_structural_score.sum(axis=1)
)

smell_structural_score = (
    smell_structural_score
    .sort_values("total_connections", ascending=False)
)

print("====================================================")
print("PASO 34. COMMUNITY SMELLS ESTRUCTURALES")
print("====================================================")

display(smell_structural_score)

smell_structural_score.to_excel(
    "community_smells_structural_score.xlsx"
)

print("\nArchivo exportado:")
print("community_smells_structural_score.xlsx")

# ============================================================
# PASO 35. CLUSTERS DE DEUDA SOCIAL
# ============================================================

import pandas as pd

cooc = pd.read_excel(
    "microcause_cooccurrence.xlsx"
)

print("====================================================")
print("PASO 35. CLUSTERS DE DEUDA SOCIAL")
print("====================================================")

top_clusters = (
    cooc
    .sort_values("frequency", ascending=False)
    .head(20)
)

display(top_clusters)

top_clusters.to_excel(
    "top_social_debt_clusters.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("top_social_debt_clusters.xlsx")

# ============================================================
# PASO 37. PUNTOS DE INTERVENCIÓN
# ============================================================

top_interventions = (
    structural_score
    .sort_values(
        "total_connections",
        ascending=False
    )
    .head(15)
)

print("====================================================")
print("PASO 37. PUNTOS DE INTERVENCIÓN")
print("====================================================")

display(top_interventions)

# ============================================================
# PASO 36. CAMINOS DE PROPAGACIÓN MICROCAUSA → SMELL → RIESGO
# ============================================================

import pandas as pd

print("====================================================")
print("PASO 36. CAMINOS DE PROPAGACIÓN MICROCAUSA → SMELL → RIESGO")
print("====================================================")

relations = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    smells = [
        s.strip()
        for s in str(row["community_smells"]).split("•")
        if s.strip() != ""
    ]

    risks = [
        r.strip()
        for r in str(row["risks"]).split("•")
        if r.strip() != ""
    ]

    for smell in smells:
        for risk in risks:
            relations.append({
                "microcause": microcause,
                "community_smell": smell,
                "risk": risk
            })

paths_df = pd.DataFrame(relations)

critical_paths = (
    paths_df
    .value_counts(
        [
            "microcause",
            "community_smell",
            "risk"
        ]
    )
    .reset_index(name="frequency")
    .sort_values("frequency", ascending=False)
)

print("\nTop 30 caminos de propagación:")
display(
    critical_paths.head(30)
)

critical_paths.to_excel(
    "critical_paths_microcause_smell_risk.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("critical_paths_microcause_smell_risk.xlsx")

# ============================================================
# PASO 37. PUNTOS DE INTERVENCIÓN ESTRATÉGICOS
# ============================================================

top_interventions = (
    structural_score
    .sort_values(
        "total_connections",
        ascending=False
    )
)

print("====================================================")
print("PASO 37. PUNTOS DE INTERVENCIÓN")
print("====================================================")

display(
    top_interventions.head(20)
)

top_interventions.to_excel(
    "top_intervention_points.xlsx"
)

print("\nArchivo exportado:")
print("top_intervention_points.xlsx")

# ============================================================
# PASO 38. PRIORIZACIÓN DE INTERVENCIONES
# ============================================================

import pandas as pd

# -------------------------------------------
# Frecuencia real
# -------------------------------------------

frequency = (
    df["primary_microcause_name"]
    .value_counts()
    .reset_index()
)

frequency.columns = [
    "microcause",
    "frequency"
]

# -------------------------------------------
# Structural score (Paso 37)
# -------------------------------------------

intervention = (
    top_interventions
    .reset_index()
)

intervention.columns = [
    "microcause",
    "community_smells",
    "risks",
    "effects",
    "total_connections"
]

# -------------------------------------------
# Combinar
# -------------------------------------------

priority = frequency.merge(
    intervention,
    on="microcause",
    how="left"
)

# -------------------------------------------
# Score adaptativo
# -------------------------------------------

priority["priority_score"] = (
    priority["frequency"]
    *
    priority["total_connections"]
)

priority = (
    priority
    .sort_values(
        "priority_score",
        ascending=False
    )
)

print("====================================================")
print("PASO 38. PRIORIZACIÓN DE INTERVENCIONES")
print("====================================================")

display(
    priority.head(20)
)

priority.to_excel(
    "adaptive_intervention_priority.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("adaptive_intervention_priority.xlsx")

# ============================================================
# FASE V. VALIDACIÓN MEDIANTE COMPETENCY QUESTIONS
# ============================================================

print("====================================================")
print("FASE V. VALIDACIÓN MEDIANTE COMPETENCY QUESTIONS")
print("====================================================")
print("Objetivo: responder las preguntas de competencia usando evidencia empírica del dataset.")

# ============================================================
# PASO 39. VALIDACIÓN EMPÍRICA DE CQ1
# ============================================================


cq1 = (
    matrix_micro_smell
    .sum(axis=0)
    .sort_values(ascending=False)
)

cq1 = cq1.reset_index()
cq1.columns = [
    "community_smell",
    "frequency"
]

display(cq1)

cq1.to_excel(
    "CQ1_community_smells.xlsx",
    index=False
)

print("\nInterpretación:")
print("Community smells más asociados a las")
print("microcausas identificadas en el dataset.")

# ============================================================
# FIGURA CQ1
# DISTRIBUCIÓN DE COMMUNITY SMELLS
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Datos CQ1
cq1 = pd.DataFrame({
    "community_smell": [
        "Missing Link",
        "Socio-Technical Congruence Gap",
        "Organizational Silo",
        "Power Distance",
        "Truck Factor",
        "Knowledge Silos",
        "Organizational Silence",
        "Prima Donnas",
        "Shared Villainy"
    ],
    "frequency": [
        2309,
        925,
        808,
        717,
        474,
        177,
        166,
        53,
        22
    ]
})

# ------------------------------------------------
# porcentaje
# ------------------------------------------------

total = cq1["frequency"].sum()

cq1["percentage"] = (
    cq1["frequency"] / total * 100
).round(1)

# ------------------------------------------------
# ordenar
# ------------------------------------------------

cq1 = cq1.sort_values(
    "frequency",
    ascending=True
)

# ------------------------------------------------
# figura
# ------------------------------------------------

fig, ax = plt.subplots(
    figsize=(12,7)
)

colors = plt.cm.Blues(
    np.linspace(
        0.45,
        0.95,
        len(cq1)
    )
)

bars = ax.barh(
    cq1["community_smell"],
    cq1["frequency"],
    color=colors
)

# ------------------------------------------------
# etiquetas
# ------------------------------------------------

for bar, freq, pct in zip(
    bars,
    cq1["frequency"],
    cq1["percentage"]
):

    ax.text(
        freq + 15,
        bar.get_y() + bar.get_height()/2,
        f"{freq:,} ({pct}%)",
        va="center",
        fontsize=10,
        fontweight="bold"
    )

# ------------------------------------------------
# estilo Q1
# ------------------------------------------------

ax.set_title(
    "Distribution of Community Smells Associated with Social Debt Causes",
    fontsize=15,
    fontweight="bold",
    pad=15
)

ax.set_xlabel(
    "Frequency",
    fontsize=12
)

ax.set_ylabel(
    "Community Smell",
    fontsize=12
)

ax.grid(
    axis="x",
    linestyle="--",
    alpha=0.3
)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.tight_layout()

# ------------------------------------------------
# exportar
# ------------------------------------------------

plt.savefig(
    "Figure_CQ1_Community_Smells.png",
    dpi=300,
    bbox_inches="tight"
)

plt.savefig(
    "Figure_CQ1_Community_Smells.pdf",
    bbox_inches="tight"
)

plt.show()

print("Figura exportada:")
print("Figure_CQ1_Community_Smells.png")
print("Figure_CQ1_Community_Smells.pdf")

# ============================================================
# RECONSTRUIR TABLA DE PRIORIZACIÓN PARA CQ2
# ============================================================

frequency = (
    df["primary_microcause_name"]
    .value_counts()
    .rename("frequency")
)

intervention = intervention.set_index("microcause")

intervention["frequency"] = frequency

intervention = intervention.fillna(0)

intervention["priority_score"] = (
    intervention["frequency"]
    *
    intervention["total_connections"]
)

intervention = (
    intervention
    .reset_index()
    .sort_values("priority_score", ascending=False)
)

display(intervention.head(20))

intervention.to_excel(
    "adaptive_intervention_priority.xlsx",
    index=False
)

# ============================================================
# PASO 40. VALIDACIÓN EMPÍRICA DE CQ2
# ============================================================

print("====================================================")
print("PASO 40. VALIDACIÓN EMPÍRICA DE CQ2")
print("====================================================")

print(
    "¿Qué causas asociadas a factores sociotécnicos "
    "influyen en la aparición de deuda social?"
)

cq2 = intervention.copy()

cq2 = cq2.sort_values(
    "priority_score",
    ascending=False
)

display(
    cq2.head(20)
)

cq2.to_excel(
    "CQ2_influential_microcauses.xlsx"
)

print("\nArchivo exportado:")
print("CQ2_influential_microcauses.xlsx")

# ============================================================
# PASO 41A. TOP EFECTOS GLOBALES
# ============================================================

print("====================================================")
print("PASO 41A. TOP EFECTOS GLOBALES")
print("====================================================")

top_effects = (
    matrix_micro_effect
    .sum(axis=0)
    .sort_values(ascending=False)
    .reset_index()
)

top_effects.columns = [
    "effect",
    "frequency"
]

display(top_effects.head(20))

top_effects.to_excel(
    "CQ3_top_effects.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ3_top_effects.xlsx")

# ============================================================
# PASO 42. VALIDACIÓN EMPÍRICA DE CQ4
# ============================================================

print("====================================================")
print("PASO 42. VALIDACIÓN EMPÍRICA DE CQ4")
print("====================================================")

records = []

for micro in matrix_micro_effect.index:

    row = matrix_micro_effect.loc[micro]

    top_effects = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    for effect, freq in top_effects.items():

        records.append([
            micro,
            effect,
            freq
        ])

cq4 = pd.DataFrame(
    records,
    columns=[
        "microcause",
        "effect",
        "frequency"
    ]
)

cq4 = cq4.sort_values(
    "frequency",
    ascending=False
)

display(cq4.head(50))

cq4.to_excel(
    "CQ4_microcause_effects.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ4_microcause_effects.xlsx")

# ============================================================
# PASO 43A. TOP ESTRATEGIAS CORRECTIVAS
# ============================================================

print("====================================================")
print("PASO 43A. TOP ESTRATEGIAS CORRECTIVAS")
print("====================================================")

top_corrective = (
    matrix_micro_corrective
    .sum(axis=0)
    .sort_values(ascending=False)
    .reset_index()
)

top_corrective.columns = [
    "corrective_strategy",
    "frequency"
]

display(top_corrective.head(30))

top_corrective.to_excel(
    "CQ5_top_corrective_strategies.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ5_top_corrective_strategies.xlsx")

# ============================================================
# PASO 43B. MICROCAUSA -> ESTRATEGIA CORRECTIVA
# ============================================================

records = []

for micro in matrix_micro_corrective.index:

    row = matrix_micro_corrective.loc[micro]

    top_strategies = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    for strategy, freq in top_strategies.items():

        records.append([
            micro,
            strategy,
            freq
        ])

cq5 = pd.DataFrame(
    records,
    columns=[
        "microcause",
        "corrective_strategy",
        "frequency"
    ]
)

cq5 = cq5.sort_values(
    "frequency",
    ascending=False
)

display(cq5.head(50))

cq5.to_excel(
    "CQ5_microcause_corrective.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ5_microcause_corrective.xlsx")

# ============================================================
# PASO 44A. TOP ESTRATEGIAS PREVENTIVAS
# ============================================================

print("====================================================")
print("PASO 44A. TOP ESTRATEGIAS PREVENTIVAS")
print("====================================================")

top_preventive = (
    matrix_micro_strategy
    .sum(axis=0)
    .sort_values(ascending=False)
    .reset_index()
)

top_preventive.columns = [
    "preventive_strategy",
    "frequency"
]

display(top_preventive.head(30))

top_preventive.to_excel(
    "CQ6_top_preventive_strategies.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ6_top_preventive_strategies.xlsx")

# ============================================================
# PASO 44B. MICROCAUSA -> ESTRATEGIA PREVENTIVA
# ============================================================

records = []

for micro in matrix_micro_strategy.index:

    row = matrix_micro_strategy.loc[micro]

    top_strategies = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    for strategy, freq in top_strategies.items():

        records.append([
            micro,
            strategy,
            freq
        ])

cq6 = pd.DataFrame(
    records,
    columns=[
        "microcause",
        "preventive_strategy",
        "frequency"
    ]
)

cq6 = cq6.sort_values(
    "frequency",
    ascending=False
)

display(cq6.head(50))

cq6.to_excel(
    "CQ6_microcause_preventive.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ6_microcause_preventive.xlsx")

# ============================================================
# PASO 46. VALIDACIÓN EMPÍRICA DE CQ7
# ============================================================

cq7 = (
    matrix_micro_smell
    .sum(axis=0)
    .sort_values(ascending=False)
    .reset_index()
)

cq7.columns = [
    "community_smell",
    "frequency"
]

display(cq7)

cq7.to_excel(
    "CQ7_community_smells.xlsx",
    index=False
)

# ============================================================
# PASO 47. VALIDACIÓN EMPÍRICA DE CQ8
# ============================================================

records = []

for smell in matrix_smell_effect.index:

    row = matrix_smell_effect.loc[smell]

    top_effects = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    for effect, freq in top_effects.items():

        records.append([
            smell,
            effect,
            freq
        ])

cq8 = pd.DataFrame(
    records,
    columns=[
        "community_smell",
        "effect",
        "frequency"
    ]
)

cq8 = cq8.sort_values(
    "frequency",
    ascending=False
)

display(cq8.head(50))

cq8.to_excel(
    "CQ8_smell_effects.xlsx",
    index=False
)

# ============================================================
# PASO 46. VALIDACIÓN EMPÍRICA DE CQ7
# ============================================================

print("====================================================")
print("PASO 46. VALIDACIÓN EMPÍRICA DE CQ7")
print("====================================================")

cq7 = (
    matrix_micro_smell
    .sum(axis=0)
    .sort_values(ascending=False)
    .reset_index()
)

cq7.columns = [
    "community_smell",
    "frequency"
]

display(cq7)

cq7.to_excel(
    "CQ7_community_smells.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ7_community_smells.xlsx")

# ============================================================
# PASO 47. VALIDACIÓN EMPÍRICA DE CQ8
# ============================================================

print("====================================================")
print("PASO 47. VALIDACIÓN EMPÍRICA DE CQ8")
print("====================================================")

records = []

for smell in matrix_smell_effect.index:

    row = matrix_smell_effect.loc[smell]

    top_effects = (
        row[row > 0]
        .sort_values(ascending=False)
        .head(5)
    )

    for effect, freq in top_effects.items():

        records.append([
            smell,
            effect,
            freq
        ])

cq8 = pd.DataFrame(
    records,
    columns=[
        "community_smell",
        "effect",
        "frequency"
    ]
)

cq8 = cq8.sort_values(
    "frequency",
    ascending=False
)

display(cq8.head(50))

cq8.to_excel(
    "CQ8_smell_effects.xlsx",
    index=False
)

print("\nArchivo exportado:")
print("CQ8_smell_effects.xlsx")

# ============================================================
# PASO 48. VALIDACIÓN DE CQ9 - INDICADORES POR MICROCAUSA
# ============================================================

print("====================================================")
print("PASO 48. VALIDACIÓN DE CQ9 - INDICADORES")
print("====================================================")

records = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    indicators = [
        ind.strip()
        for ind in str(row["indicators"]).split("•")
        if ind.strip() != ""
    ]

    for indicator in indicators:

        records.append({
            "microcause": microcause,
            "indicator": indicator
        })

cq9_df = pd.DataFrame(records)

cq9 = (
    cq9_df
    .value_counts(["microcause", "indicator"])
    .reset_index(name="frequency")
    .sort_values("frequency", ascending=False)
)

display(cq9.head(50))

cq9.to_excel(
    "CQ9_microcause_indicators.xlsx",
    index=False
)

# ============================================================
# PASO 49. VALIDACIÓN DE CQ10 - MÉTRICAS POR MICROCAUSA
# ============================================================

print("====================================================")
print("PASO 49. VALIDACIÓN DE CQ10 - MÉTRICAS")
print("====================================================")

records = []

for _, row in df.iterrows():

    microcause = row["primary_microcause_name"]

    metrics = [
        metric.strip()
        for metric in str(row["metrics"]).split("•")
        if metric.strip() != ""
    ]

    for metric in metrics:

        records.append({
            "microcause": microcause,
            "metric": metric
        })

cq10_df = pd.DataFrame(records)

cq10 = (
    cq10_df
    .value_counts(["microcause", "metric"])
    .reset_index(name="frequency")
    .sort_values("frequency", ascending=False)
)

display(cq10.head(50))

cq10.to_excel(
    "CQ10_microcause_metrics.xlsx",
    index=False
)

# ============================================================
# PASO 50. TABLA MAESTRA DE VALIDACIÓN DE CQs
# ============================================================

cq_summary = pd.DataFrame([

["CQ1",
 "Which community smells are associated with socio-technical factors?",
 "Community Smells",
 "CQ1_community_smells.xlsx",
 "Validated"],

["CQ2",
 "Which causes influence social debt?",
 "Priority Microcauses",
 "CQ2_influential_microcauses.xlsx",
 "Validated"],

["CQ3",
 "Which socio-technical factors are affected?",
 "Effects and Risks",
 "CQ3_top_effects.xlsx / CQ3_top_risks.xlsx",
 "Validated"],

["CQ4",
 "What effects does a cause produce?",
 "Microcause → Effect",
 "CQ4_microcause_effects.xlsx",
 "Validated"],

["CQ5",
 "Which corrective strategies are associated with effects?",
 "Microcause → Corrective Strategy",
 "CQ5_microcause_corrective.xlsx",
 "Validated"],

["CQ6",
 "Which preventive strategies can be applied?",
 "Microcause → Preventive Strategy",
 "CQ6_microcause_preventive.xlsx",
 "Validated"],

["CQ7",
 "Which community smells are associated with causes?",
 "Community Smells",
 "CQ7_community_smells.xlsx",
 "Validated"],

["CQ8",
 "What negative effects does a community smell generate?",
 "Smell → Effect",
 "CQ8_smell_effects.xlsx",
 "Validated"],

["CQ9",
 "Which indicators detect a cause?",
 "Cause → Indicator",
 "CQ9_microcause_indicators.xlsx",
 "Validated"],

["CQ10",
 "Which metrics quantify the impact of a cause?",
 "Cause → Metric",
 "CQ10_microcause_metrics.xlsx",
 "Validated"]

],
columns=[
    "CQ",
    "Question",
    "Evidence",
    "Artifact",
    "Status"
])

display(cq_summary)

cq_summary.to_excel(
    "CQ_validation_summary.xlsx",
    index=False
)

print("Archivo exportado:")
print("CQ_validation_summary.xlsx")

# ============================================================
# FASE VI. CONSTRUCCIÓN DEL MODELO ADAPTATIVO FINAL
# ============================================================

print("====================================================")
print("FASE VI. CONSTRUCCIÓN DEL MODELO ADAPTATIVO FINAL")
print("====================================================")
print("Objetivo: construir reglas y rutas de inferencia para soporte a decisiones sobre deuda social.")

# ============================================================
# PASO 50. TABLA MAESTRA DE VALIDACIÓN DE CQs
# ============================================================

cq_summary = pd.DataFrame([

["CQ1",
 "Which community smells are associated with socio-technical factors?",
 "Community Smells",
 "CQ1_community_smells.xlsx",
 "Validated"],

["CQ2",
 "Which causes influence social debt?",
 "Priority Microcauses",
 "CQ2_influential_microcauses.xlsx",
 "Validated"],

["CQ3",
 "Which socio-technical factors are affected?",
 "Effects and Risks",
 "CQ3_top_effects.xlsx / CQ3_top_risks.xlsx",
 "Validated"],

["CQ4",
 "What effects does a cause produce?",
 "Microcause → Effect",
 "CQ4_microcause_effects.xlsx",
 "Validated"],

["CQ5",
 "Which corrective strategies are associated with effects?",
 "Microcause → Corrective Strategy",
 "CQ5_microcause_corrective.xlsx",
 "Validated"],

["CQ6",
 "Which preventive strategies can be applied?",
 "Microcause → Preventive Strategy",
 "CQ6_microcause_preventive.xlsx",
 "Validated"],

["CQ7",
 "Which community smells are associated with causes?",
 "Community Smells",
 "CQ7_community_smells.xlsx",
 "Validated"],

["CQ8",
 "What negative effects does a community smell generate?",
 "Smell → Effect",
 "CQ8_smell_effects.xlsx",
 "Validated"],

["CQ9",
 "Which indicators detect a cause?",
 "Cause → Indicator",
 "CQ9_microcause_indicators.xlsx",
 "Validated"],

["CQ10",
 "Which metrics quantify the impact of a cause?",
 "Cause → Metric",
 "CQ10_microcause_metrics.xlsx",
 "Validated"]

],
columns=[
    "CQ",
    "Question",
    "Evidence",
    "Artifact",
    "Status"
])

display(cq_summary)

cq_summary.to_excel(
    "CQ_validation_summary.xlsx",
    index=False
)

print("Archivo exportado:")
print("CQ_validation_summary.xlsx")